import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAdmin } from '@/lib/admin-auth';
import { createAdminClient } from '@/utils/supabase/admin';
import { createPurchaseOrder, updatePurchaseOrderStatus } from '@/app/admin-dashboard/purchase-order-actions';

const STATUS_LABELS: Record<string, string> = { draft: 'Draft', sent: 'Sent', ordered: 'Ordered', partially_received: 'Partially received', received: 'Received', cancelled: 'Cancelled' };

export default async function PurchaseOrdersPage({ params }: { params: Promise<{ project: string }> }) {
  await requireAdmin();
  const { project: slug } = await params;
  const supabase = createAdminClient();
  const { data: project } = await supabase.from('projects').select('id, slug, project_code, client_name').eq('slug', slug).maybeSingle();
  if (!project) notFound();
  const [{ data: items }, { data: orders }] = await Promise.all([
    supabase.from('procurement_items').select('id, description, quantity, unit, estimated_unit_cost, estimated_total, status, supplier_id, suppliers(name)').eq('project_id', project.id).not('status', 'in', '(received,cancelled)').order('created_at', { ascending: false }),
    supabase.from('purchase_orders').select('id, po_number, status, subtotal, expected_delivery, ordered_at, supplier_id, suppliers(name), purchase_order_lines(id, procurement_item_id, description, quantity, unit, unit_cost, line_total)').eq('project_id', project.id).order('created_at', { ascending: false }),
  ]);
  const { data: suppliers } = await supabase.from('suppliers').select('id, name').eq('active', true).order('name');
  const availableItems = items ?? [];
  return <main className="min-h-screen bg-stone-50 px-6 py-10"><div className="mx-auto max-w-7xl">
    <div className="mb-8 flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-stone-500">{project.project_code} · {project.client_name}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-stone-900">Purchase Orders</h1><p className="mt-1 text-sm text-stone-500">Group approved procurement items by supplier and move them into ordered status.</p></div><Link href={`/admin-dashboard/${slug}/procurement`} className="rounded-full border border-stone-300 bg-white px-4 py-2 text-sm font-medium">Back to Procurement</Link></div>
    <section className="mb-8 rounded-3xl border border-stone-200 bg-white p-6"><h2 className="text-lg font-semibold">Create purchase order</h2><p className="mt-1 text-sm text-stone-500">Choose a supplier and the items to purchase together.</p>{!suppliers?.length ? <p className="mt-4 text-sm text-amber-700">Add an active supplier before creating a purchase order.</p> : !availableItems.length ? <p className="mt-4 text-sm text-stone-500">No open procurement items are available.</p> : <form action={async (formData) => { 'use server'; await createPurchaseOrder({ projectSlug: slug, supplierId: String(formData.get('supplierId')), itemIds: formData.getAll('itemIds').map(String), expectedDelivery: String(formData.get('expectedDelivery') || ''), notes: String(formData.get('notes') || '') }); }} className="mt-5 space-y-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Supplier<select name="supplierId" required className="mt-1 w-full rounded-xl border border-stone-300 px-3 py-2 font-normal"><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-medium">Expected delivery<input type="date" name="expectedDelivery" className="mt-1 w-full rounded-xl border border-stone-300 px-3 py-2 font-normal" /></label></div><div><p className="text-sm font-medium">Items</p><div className="mt-2 grid gap-2 md:grid-cols-2">{availableItems.map(item=><label key={item.id} className="flex gap-3 rounded-xl border border-stone-200 p-3 text-sm"><input type="checkbox" name="itemIds" value={item.id} className="mt-1" /><span><strong>{item.description}</strong><span className="block text-xs text-stone-500">{item.quantity} {item.unit} · KES {Number(item.estimated_total).toLocaleString()}</span></span></label>)}</div></div><label className="block text-sm font-medium">Notes<textarea name="notes" rows={2} className="mt-1 w-full rounded-xl border border-stone-300 px-3 py-2 font-normal" /></label><button className="rounded-full bg-stone-900 px-5 py-2.5 text-sm font-semibold text-white">Create purchase order</button></form>}</section>
    <section className="overflow-hidden rounded-3xl border border-stone-200 bg-white"><div className="border-b border-stone-200 px-6 py-4"><h2 className="font-semibold">Purchase order history</h2></div>{!orders?.length ? <p className="p-6 text-sm text-stone-500">No purchase orders created yet.</p> : <div className="divide-y divide-stone-100">{orders.map(po=><div key={po.id} className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{po.po_number}</p><p className="text-sm text-stone-500 mt-1">{po.suppliers?.name || 'Supplier'} · KES {Number(po.subtotal).toLocaleString()}</p></div><form action={async (formData)=>{ 'use server'; await updatePurchaseOrderStatus({ purchaseOrderId: po.id, status: String(formData.get('status')) }); }} className="flex items-center gap-2"><select name="status" defaultValue={po.status} className="rounded-xl border border-stone-300 px-3 py-2 text-sm">{Object.entries(STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="rounded-xl border border-stone-300 px-3 py-2 text-sm">Update</button></form></div><div className="mt-4 grid gap-2 md:grid-cols-2">{po.purchase_order_lines.map(line=><div key={line.id} className="rounded-xl bg-stone-50 p-3 text-sm"><p className="font-medium">{line.description}</p><p className="text-xs text-stone-500 mt-1">{line.quantity} {line.unit} · KES {Number(line.line_total).toLocaleString()}</p></div>)}</div></div>)}</div>}</section>
  </div></main>;
}
